# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-22 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0006_compensate_for_0003_bytestring_bug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data stworzenia')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Data modyfikacji')),
                ('description', models.TextField(verbose_name='Treść')),
                ('name', models.TextField(verbose_name='Nazwa')),
                ('set', models.CharField(max_length=120, verbose_name='Kolekcja')),
                ('Count', models.IntegerField(verbose_name='Ilosć')),
                ('views_no', models.IntegerField(verbose_name='Ilosć odsłon')),
                ('user_possession', models.IntegerField(verbose_name='Ilosć posiadaczy')),
                ('likes', models.IntegerField(verbose_name='Ilosć like')),
                ('publicated', models.DateTimeField(verbose_name='Data wydania')),
                ('rewers_photo', models.URLField(verbose_name='Zdjęcie rewersu')),
                ('awers_photo', models.URLField(verbose_name='Zdjęcie awersu')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.Country', verbose_name='Kraj pochodzenia')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CollectionSubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nazwa')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nazwa')),
            ],
        ),
        migrations.AddField(
            model_name='collectionsubtype',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.CollectionType', verbose_name='Typ'),
        ),
        migrations.AddField(
            model_name='collection',
            name='subtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.CollectionType', verbose_name='Typ'),
        ),
    ]
