# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-22 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_add_timestamps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ('-created',), 'verbose_name': 'Colection', 'verbose_name_plural': 'Collections'},
        ),
        migrations.AlterModelOptions(
            name='collectionsubtype',
            options={'ordering': ('-created',), 'verbose_name': 'Subtype', 'verbose_name_plural': 'Subtypes'},
        ),
        migrations.AlterModelOptions(
            name='collectiontype',
            options={'ordering': ('-created',), 'verbose_name': 'Type', 'verbose_name_plural': 'Types'},
        ),
        migrations.AlterField(
            model_name='collection',
            name='Count',
            field=models.IntegerField(verbose_name='Count'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='awers_photo',
            field=models.URLField(verbose_name='Awers photo'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.Country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='likes',
            field=models.IntegerField(verbose_name='Likes number'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='publicated',
            field=models.DateTimeField(verbose_name='Publication Date'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='rewers_photo',
            field=models.URLField(verbose_name='Rewers photo'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='set',
            field=models.CharField(max_length=120, verbose_name='Collection'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='subtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.CollectionSubType', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='user_possession',
            field=models.IntegerField(verbose_name='User possesses'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='views_no',
            field=models.IntegerField(verbose_name='Views number'),
        ),
        migrations.AlterField(
            model_name='collectionsubtype',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='collectionsubtype',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.CollectionType', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='collectiontype',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Name'),
        ),
    ]
