# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-31 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20170131_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Create date')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modification date')),
                ('name', models.CharField(max_length=120, verbose_name='Set')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='collection',
            name='set',
        ),
        migrations.AlterField(
            model_name='collection',
            name='user_possession',
            field=models.IntegerField(verbose_name='User possession'),
        ),
        migrations.AddField(
            model_name='collectionsubtype',
            name='set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.Set', verbose_name='Set'),
        ),
    ]
