# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-06 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_auto_20170131_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
        migrations.RemoveField(
            model_name='collectionsubtype',
            name='set',
        ),
        migrations.RemoveField(
            model_name='collectiontype',
            name='subtype',
        ),
        migrations.AddField(
            model_name='collection',
            name='set',
            field=models.CharField(max_length=120, null=True, verbose_name='Collection'),
        ),
        migrations.AddField(
            model_name='collection',
            name='subtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.CollectionSubType', verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='collectionsubtype',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.CollectionType', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='user_possession',
            field=models.IntegerField(verbose_name='User possesses'),
        ),
        migrations.DeleteModel(
            name='Set',
        ),
    ]
